In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from catboost import CatBoostRegressor
from sklearn.linear_model import LinearRegression
from typing import Optional
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
import optuna

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/model_price_car/train.csv")
df

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

добавить фичу: страна,

In [ ]:
def parse_engine(feature_str):
    # Извлекаем мощность
    power_match = re.search(r'(\d+\.?\d*)HP', feature_str)
    power = float(power_match.group(1)) if power_match else None

    # Извлекаем объем двигателя (как float)
    displacement_match = re.search(r'(\d+\.?\d*)L', feature_str)
    displacement = float(displacement_match.group(1)) if displacement_match else None

    # Извлекаем количество цилиндров (как int)
    cylinders = None
    cylinders_match = re.search(r'(\d+)\s*Cylinder', feature_str)
    if cylinders_match:
        cylinders = int(cylinders_match.group(1))
    else:
        v_match = re.search(r'V(\d+)', feature_str)
        if v_match:
            cylinders = int(v_match.group(1))



    # Возвращаем ТОЛЬКО 4 значения: мощность, объем, цилиндры, топливо
    return pd.Series([power, displacement, cylinders])

# Применяем функцию (только 4 колонки)
df[['power_hp', 'engine_volume_l', 'cylinders_count']] = df['engine'].apply(parse_engine)

In [ ]:
df = df.drop('engine', axis=1)

In [ ]:
df['accident'] = df['accident'].apply(lambda x: 1 if pd.notna(x) and x != "None reported" else 0)
df

,id,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count
0,0,MINI,Cooper S Base,2007,213000,Gasoline,A/T,Yellow,Gray,0,Yes,4200,172.0,1.6,4.0
1,1,Lincoln,LS V8,2002,143250,Gasoline,A/T,Silver,Beige,1,Yes,4999,252.0,3.9,8.0
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,A/T,Blue,Gray,0,Yes,13900,320.0,5.3,8.0
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,420.0,5.0,8.0
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,7-Speed A/T,Black,Beige,0,Yes,97500,208.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,Transmission w/Dual Shift Mode,White,Beige,0,Yes,27500,420.0,6.2,8.0
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,8-Speed A/T,White,Black,1,Yes,30000,385.0,3.0,6.0
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,7-Speed A/T,White,Black,0,Yes,86900,469.0,4.0,8.0
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,1-Speed Automatic,Daytona Gray Pearl Effect,Black,0,NaN,84900,NaN,3.0,NaN
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,Transmission w/Dual Shift Mode,White,Black,0,Yes,28995,252.0,2.0,4.0

In [ ]:
def parse_transmission(trans_str):
    if pd.isna(trans_str):
        return pd.Series([None, None])

    trans_str = str(trans_str)

    # 1. Определяем тип (автомат или механика)
    is_automatic = 1  # по умолчанию автомат

    # Признаки механики
    manual_keywords = ['M/T', 'Manual']
    if any(keyword in trans_str for keyword in manual_keywords):
        is_automatic = 0

    # Особые случаи
    if 'CVT' in trans_str:  # Вариатор - тоже автомат
        is_automatic = 1

    # 2. Извлекаем количество скоростей
    # Ищем цифру перед словами Speed, A/T, M/T, Automatic
    speed_match = re.search(r'(\d+)-?\s*(Speed|A/T|M/T|Automatic)', trans_str)

    if speed_match:
        speeds = int(speed_match.group(1))
    elif 'A/T' in trans_str and 'Speed' not in trans_str:
        # Просто "A/T" - без указания скоростей
        speeds = 4  # или None, или 5 - зависит от данных
    elif 'M/T' in trans_str and 'Speed' not in trans_str:
        # Просто "M/T" - механика без указания скоростей
        speeds = 5  # обычно 5-ступка
    elif 'Automatic' in trans_str and 'Speed' not in trans_str:
        # Просто "Automatic" без цифры
        speeds = 4
    elif 'CVT' in trans_str:
        speeds = 0  # CVT не имеет фиксированных скоростей
    else:
        speeds = None

    return pd.Series([is_automatic, speeds])

# Применяем
df[['is_automatic', 'gears_count']] = df['transmission'].apply(parse_transmission)
df

,id,brand,model,model_year,milage,fuel_type,transmission,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,0,MINI,Cooper S Base,2007,213000,Gasoline,A/T,Yellow,Gray,0,Yes,4200,172.0,1.6,4.0,1.0,4.0
1,1,Lincoln,LS V8,2002,143250,Gasoline,A/T,Silver,Beige,1,Yes,4999,252.0,3.9,8.0,1.0,4.0
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,A/T,Blue,Gray,0,Yes,13900,320.0,5.3,8.0,1.0,4.0
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,Transmission w/Dual Shift Mode,Black,Black,0,Yes,45000,420.0,5.0,8.0,1.0,NaN
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,7-Speed A/T,Black,Beige,0,Yes,97500,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,Transmission w/Dual Shift Mode,White,Beige,0,Yes,27500,420.0,6.2,8.0,1.0,NaN
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,8-Speed A/T,White,Black,1,Yes,30000,385.0,3.0,6.0,1.0,8.0
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,7-Speed A/T,White,Black,0,Yes,86900,469.0,4.0,8.0,1.0,7.0
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,1-Speed Automatic,Daytona Gray Pearl Effect,Black,0,NaN,84900,NaN,3.0,NaN,1.0,1.0
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,Transmission w/Dual Shift Mode,White,Black,0,Yes,28995,252.0,2.0,4.0,1.0,NaN

In [ ]:
df = df.drop('transmission', axis=1)
df

,id,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,0,MINI,Cooper S Base,2007,213000,Gasoline,Yellow,Gray,0,Yes,4200,172.0,1.6,4.0,1.0,4.0
1,1,Lincoln,LS V8,2002,143250,Gasoline,Silver,Beige,1,Yes,4999,252.0,3.9,8.0,1.0,4.0
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,Blue,Gray,0,Yes,13900,320.0,5.3,8.0,1.0,4.0
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,Black,Black,0,Yes,45000,420.0,5.0,8.0,1.0,NaN
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,Black,Beige,0,Yes,97500,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,White,Beige,0,Yes,27500,420.0,6.2,8.0,1.0,NaN
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,White,Black,1,Yes,30000,385.0,3.0,6.0,1.0,8.0
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,White,Black,0,Yes,86900,469.0,4.0,8.0,1.0,7.0
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,Daytona Gray Pearl Effect,Black,0,NaN,84900,NaN,3.0,NaN,1.0,1.0
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,White,Black,0,Yes,28995,252.0,2.0,4.0,1.0,NaN

In [ ]:
df['model'].value_counts()

model
F-150 XLT                        2945
M3 Base                          2229
Camaro 2SS                       1709
M4 Base                          1622
Mustang GT Premium               1526
                                 ...
ForTwo Pure                         2
XLR Base                            1
X5 3.0i                             1
X5 xDrive40e                        1
Integra w/A-Spec Tech Package       1
Name: count, Length: 1897, dtype: int64

In [ ]:
df['model'] = df['model'].str.split().str[0]

In [ ]:
df = df.drop('id', axis=1)
df

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,MINI,Cooper,2007,213000,Gasoline,Yellow,Gray,0,Yes,4200,172.0,1.6,4.0,1.0,4.0
1,Lincoln,LS,2002,143250,Gasoline,Silver,Beige,1,Yes,4999,252.0,3.9,8.0,1.0,4.0
2,Chevrolet,Silverado,2002,136731,E85 Flex Fuel,Blue,Gray,0,Yes,13900,320.0,5.3,8.0,1.0,4.0
3,Genesis,G90,2017,19500,Gasoline,Black,Black,0,Yes,45000,420.0,5.0,8.0,1.0,NaN
4,Mercedes-Benz,Metris,2021,7388,Gasoline,Black,Beige,0,Yes,97500,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade,2017,49000,Gasoline,White,Beige,0,Yes,27500,420.0,6.2,8.0,1.0,NaN
188529,Mercedes-Benz,AMG,2018,28600,Gasoline,White,Black,1,Yes,30000,385.0,3.0,6.0,1.0,8.0
188530,Mercedes-Benz,AMG,2021,13650,Gasoline,White,Black,0,Yes,86900,469.0,4.0,8.0,1.0,7.0
188531,Audi,S5,2022,13895,Gasoline,Daytona Gray Pearl Effect,Black,0,NaN,84900,NaN,3.0,NaN,1.0,1.0
188532,Porsche,Macan,2016,59500,Gasoline,White,Black,0,Yes,28995,252.0,2.0,4.0,1.0,NaN

In [ ]:
df['clean_title'] = df['clean_title'].apply(lambda x: 1 if x == "Yes" else 0)
df

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,MINI,Cooper,2007,213000,Gasoline,Yellow,Gray,0,1,4200,172.0,1.6,4.0,1.0,4.0
1,Lincoln,LS,2002,143250,Gasoline,Silver,Beige,1,1,4999,252.0,3.9,8.0,1.0,4.0
2,Chevrolet,Silverado,2002,136731,E85 Flex Fuel,Blue,Gray,0,1,13900,320.0,5.3,8.0,1.0,4.0
3,Genesis,G90,2017,19500,Gasoline,Black,Black,0,1,45000,420.0,5.0,8.0,1.0,NaN
4,Mercedes-Benz,Metris,2021,7388,Gasoline,Black,Beige,0,1,97500,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade,2017,49000,Gasoline,White,Beige,0,1,27500,420.0,6.2,8.0,1.0,NaN
188529,Mercedes-Benz,AMG,2018,28600,Gasoline,White,Black,1,1,30000,385.0,3.0,6.0,1.0,8.0
188530,Mercedes-Benz,AMG,2021,13650,Gasoline,White,Black,0,1,86900,469.0,4.0,8.0,1.0,7.0
188531,Audi,S5,2022,13895,Gasoline,Daytona Gray Pearl Effect,Black,0,0,84900,NaN,3.0,NaN,1.0,1.0
188532,Porsche,Macan,2016,59500,Gasoline,White,Black,0,1,28995,252.0,2.0,4.0,1.0,NaN

In [ ]:
base_colors = ['Black', 'White', 'Gray', 'Silver', 'Blue', 'Red',
               'Green', 'Gold', 'Brown', 'Orange', 'Beige', 'Yellow']

df['ext_col'] = df['ext_col'].apply(
    lambda x: next((c for c in base_colors if c.lower() in str(x).lower()), 'Other')
)

# Смотрим, сколько 'Other' получилось
print(f"Other цветов: {(df['ext_col'] == 'Other').sum()}")
print(df['ext_col'].value_counts())

Other цветов: 4522
ext_col
Black     53917
White     47945
Gray      26669
Silver    18809
Blue      15837
Red       11795
Other      4522
Green      2948
Gold       1668
Brown      1185
Orange     1148
Beige      1096
Yellow      994
Name: count, dtype: int64

In [ ]:
df

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,MINI,Cooper,2007,213000,Gasoline,Yellow,Gray,0,1,4200,172.0,1.6,4.0,1.0,4.0
1,Lincoln,LS,2002,143250,Gasoline,Silver,Beige,1,1,4999,252.0,3.9,8.0,1.0,4.0
2,Chevrolet,Silverado,2002,136731,E85 Flex Fuel,Blue,Gray,0,1,13900,320.0,5.3,8.0,1.0,4.0
3,Genesis,G90,2017,19500,Gasoline,Black,Black,0,1,45000,420.0,5.0,8.0,1.0,NaN
4,Mercedes-Benz,Metris,2021,7388,Gasoline,Black,Beige,0,1,97500,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade,2017,49000,Gasoline,White,Beige,0,1,27500,420.0,6.2,8.0,1.0,NaN
188529,Mercedes-Benz,AMG,2018,28600,Gasoline,White,Black,1,1,30000,385.0,3.0,6.0,1.0,8.0
188530,Mercedes-Benz,AMG,2021,13650,Gasoline,White,Black,0,1,86900,469.0,4.0,8.0,1.0,7.0
188531,Audi,S5,2022,13895,Gasoline,Gray,Black,0,0,84900,NaN,3.0,NaN,1.0,1.0
188532,Porsche,Macan,2016,59500,Gasoline,White,Black,0,1,28995,252.0,2.0,4.0,1.0,NaN

In [ ]:
df.isna().sum()

brand                  0
model                  0
model_year             0
milage                 0
fuel_type           5083
ext_col                0
int_col                0
accident               0
clean_title            0
price                  0
power_hp           33259
engine_volume_l    14214
cylinders_count    21763
is_automatic           0
gears_count        19782
dtype: int64

In [ ]:
df['fuel_type'] = df['fuel_type'].replace(['-', '–', '', 'None', 'none', 'NULL'], np.nan)
df['fuel_type'].value_counts()

fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64

In [ ]:
X = df.drop('price', axis=1)
y = df['price']

In [ ]:
X.isna().sum()

brand                  0
model                  0
model_year             0
milage                 0
fuel_type           5864
ext_col                0
int_col                0
accident               0
clean_title            0
power_hp           33259
engine_volume_l    14214
cylinders_count    21763
is_automatic           0
gears_count        19782
dtype: int64

In [ ]:
categor_feature = X.select_dtypes(['object']).columns.to_list()
numerical_feature = X.select_dtypes([np.number]).columns.to_list()

for col in categor_feature:
  X[col] = X[col].fillna('Missing')

for col in numerical_feature:
    X[col] = X[col].fillna(
        X.groupby(['brand', 'model'])[col].transform('median')
    )

    X[col] = X[col].fillna(
        X.groupby('brand')[col].transform('median')
    )

    if X[col].isna().any():
        global_median = X[col].median()
        X[col] = X[col].fillna(global_median)

In [ ]:
X.isna().sum()

brand              0
model              0
model_year         0
milage             0
fuel_type          0
ext_col            0
int_col            0
accident           0
clean_title        0
power_hp           0
engine_volume_l    0
cylinders_count    0
is_automatic       0
gears_count        0
dtype: int64

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,power_hp,engine_volume_l,cylinders_count,is_automatic,gears_count
0,MINI,Cooper,2007,213000,Gasoline,Yellow,Gray,0,1,172.0,1.6,4.0,1.0,4.0
1,Lincoln,LS,2002,143250,Gasoline,Silver,Beige,1,1,252.0,3.9,8.0,1.0,4.0
2,Chevrolet,Silverado,2002,136731,E85 Flex Fuel,Blue,Gray,0,1,320.0,5.3,8.0,1.0,4.0
3,Genesis,G90,2017,19500,Gasoline,Black,Black,0,1,420.0,5.0,8.0,1.0,8.0
4,Mercedes-Benz,Metris,2021,7388,Gasoline,Black,Beige,0,1,208.0,2.0,4.0,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade,2017,49000,Gasoline,White,Beige,0,1,420.0,6.2,8.0,1.0,8.0
188529,Mercedes-Benz,AMG,2018,28600,Gasoline,White,Black,1,1,385.0,3.0,6.0,1.0,8.0
188530,Mercedes-Benz,AMG,2021,13650,Gasoline,White,Black,0,1,469.0,4.0,8.0,1.0,7.0
188531,Audi,S5,2022,13895,Gasoline,Gray,Black,0,0,333.0,3.0,6.0,1.0,1.0
188532,Porsche,Macan,2016,59500,Gasoline,White,Black,0,1,252.0,2.0,4.0,1.0,7.0

In [ ]:
class Preprocessing:

  BASE_COLORS = ['Black', 'White', 'Gray', 'Silver', 'Blue', 'Red',
                   'Green', 'Gold', 'Brown', 'Orange', 'Beige', 'Yellow']

  FUEL_MAP = {
        'flex': 'Flex Fuel', 'flex fuel': 'Flex Fuel',
        'e85': 'Flex Fuel', 'ethanol': 'Flex Fuel',
        'petrol': 'Gasoline'
    }

  MISSING_VALUES = ['-', '–', '', 'None', 'none', 'NULL', 'N/A', 'na']

  def __init__(self, df:pd.DataFrame, is_linear: bool = True) -> None:
      self.df = df
      self.is_linear = is_linear

  def parse_engine(self, feature_str):

    power_match = re.search(r'(\d+\.?\d*)HP', feature_str)
    power = float(power_match.group(1)) if power_match else None

    displacement_match = re.search(r'(\d+\.?\d*)L', feature_str)
    displacement = float(displacement_match.group(1)) if displacement_match else None

    cylinders = None
    cylinders_match = re.search(r'(\d+)\s*Cylinder', feature_str)
    if cylinders_match:
        cylinders = int(cylinders_match.group(1))
    else:
        v_match = re.search(r'V(\d+)', feature_str)
        if v_match:
            cylinders = int(v_match.group(1))

    fuel_match = re.search(r'(Gasoline|Diesel|Electric|Petrol|Hybrid|Flex|Flex Fuel|E85|Ethanol)', feature_str, re.IGNORECASE)
    if fuel_match:
        fuel = fuel_match.group(1).capitalize()
        if fuel.lower() in ['Flex', 'Flex fuel', 'E85', 'Ethanol']:
            fuel = 'Flex Fuel'
        elif fuel.lower() == 'Petrol':
            fuel = 'Gasoline'
    else:
        fuel = None
    return pd.Series([power, displacement, cylinders, fuel])

  def parse_transmission(self, trans_str):
    if pd.isna(trans_str):
        return pd.Series([None, None])

    trans_str = str(trans_str)

    is_automatic = 1

    manual_keywords = ['M/T', 'Manual']
    if any(keyword in trans_str for keyword in manual_keywords):
        is_automatic = 0

    if 'CVT' in trans_str:
        is_automatic = 1

    speed_match = re.search(r'(\d+)-?\s*(Speed|A/T|M/T|Automatic)', trans_str)

    if speed_match:
        speeds = int(speed_match.group(1))
    elif 'A/T' in trans_str and 'Speed' not in trans_str:
        speeds = 4
    elif 'M/T' in trans_str and 'Speed' not in trans_str:
        speeds = 5
    elif 'Automatic' in trans_str and 'Speed' not in trans_str:
        speeds = 4
    elif 'CVT' in trans_str:
        speeds = 0
    else:
        speeds = None

    return pd.Series([is_automatic, speeds])


  def extract_color(self, name_feature: str):
      base_colors = ['Black', 'White', 'Gray', 'Silver', 'Blue', 'Red',
                'Green', 'Gold', 'Brown', 'Orange', 'Beige', 'Yellow']

      self.df[name_feature] = self.df[name_feature].apply(
          lambda x: next((c for c in base_colors if c.lower() in str(x).lower()), 'Other')
      )
      return self.df

  def detect_missing(self):
    categor_feature = self.df.select_dtypes(['object']).columns.to_list()
    numerical_feature = self.df.select_dtypes([np.number]).columns.to_list()

    for col in categor_feature:
      self.df[col] = self.df[col].fillna('Missing')

    for col in numerical_feature:
        self.df[col] = self.df[col].fillna(
            self.df.groupby(['brand', 'model'])[col].transform('median')
        )

        self.df[col] = self.df[col].fillna(
            self.df.groupby('brand')[col].transform('median')
        )

        if self.df[col].isna().any():
            global_median = self.df[col].median()
            self.df[col] = self.df[col].fillna(global_median)
    return self.df

  def make_preprocessing(self) -> pd.DataFrame:
    self.df = self.df.drop("id", axis=1)
    self.df[['power_hp', 'engine_volume_l', 'cylinders_count', 'type_fuel']] = self.df['engine'].apply(self.parse_engine)
    self.df = self.df.drop('engine', axis=1)
    self.df['accident'] = self.df['accident'].apply(lambda x: 1 if pd.notna(x) and x != "None reported" else 0)
    self.df['clean_title'] = self.df['clean_title'].apply(lambda x: 1 if x == 'Yes' else 0)
    self.df[['is_automatic', 'gears_count']] = self.df['transmission'].apply(self.parse_transmission)
    self.df = self.df.drop('transmission', axis=1)
    self.df['model'] = self.df['model'].str.split().str[0]
    self.df = self.extract_color('ext_col')
    self.df = self.extract_color('int_col')
    self.df['fuel_type'] = self.df['fuel_type'].replace(['-', '–', '', 'None', 'none', 'NULL'], np.nan)
    self.df = self.detect_missing()
    return self.df

In [ ]:
from optuna.pruners import HyperbandPruner
class Modeling:

  HYPERPARAMS = {}

  def __init__(self, model:CatBoostRegressor) -> None:
     self.model = model
     self.test_pred = None

  @staticmethod
  def show_metrics(y_pred, y_true):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = root_mean_squared_error(y_true, y_pred)

    print(f"mae: {mae}")
    print(f"mse: {mse}")
    print(f"rmse: {rmse}")

  def find_hyperparams(self, df: pd.DataFrame, n_trials: int = 10 ) -> None:
    X = df.drop('price', axis=1)
    y = df['price']

    cat_features= df.select_dtypes(['object']).columns.to_list()

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

    def objective(trial: optuna.Trial) -> float:
      params = {
                'iterations':        trial.suggest_int('iterations', 500, 2000),
                'learning_rate':     trial.suggest_float('learning_rate', 1e-3, 0.3, log=True),
                'depth':             trial.suggest_int('depth', 4, 10),
                'l2_leaf_reg':       trial.suggest_float('l2_leaf_reg', 1e-2, 10.0, log=True),
                'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 1.0),
                'random_strength':   trial.suggest_float('random_strength', 1e-2, 10.0, log=True),
                'border_count':      trial.suggest_int('border_count', 32, 255),
                'verbose': 100,
                'random_seed': 42,
                'loss_function': 'RMSE',
            }

      model = CatBoostRegressor(**params)
      model.fit(X_train, y_train, cat_features=cat_features, eval_set = (X_val, y_val), verbose=100)
      y_pred = model.predict(X_val)
      return mean_absolute_error(y_val, y_pred)

    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

    self.HYPERPARAMS = study.best_params
    print(f"Best params: {self.HYPERPARAMS}")
    print(f"Best score: {study.best_value}")


  def model_fit_predict(self, df: pd.DataFrame, ) -> None:
    self.model = self.model(**self.HYPERPARAMS)
    X = df.drop('price', axis=1)
    cat_features = df.select_dtypes(['object']).columns.to_list()
    y = df['price']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

    if len(self.HYPERPARAMS) == 0:
      print("Подбор гиперпараметров ещё не реализован")
      self.model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_val, y_val), verbose=100)
      self.test_pred = self.model.predict(X_val)
      self.show_metrics(self.test_pred, y_val)
    else:
      self.model = self.model(**self.HYPERPARAMS)
      self.model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_val, y_val), verbose=100)
      self.test_pred = self.model.predict(X_val)
      self.show_metrics(self.test_pred, y_val)

In [ ]:
res_df = Preprocessing(pd.read_csv("/content/drive/MyDrive/model_price_car/train.csv"))
res_df = res_df.make_preprocessing()
res_df

,brand,model,model_year,milage,fuel_type,ext_col,int_col,accident,clean_title,price,power_hp,engine_volume_l,cylinders_count,type_fuel,is_automatic,gears_count
0,MINI,Cooper,2007,213000,Gasoline,Yellow,Gray,0,1,4200,172.0,1.6,4.0,Gasoline,1.0,4.0
1,Lincoln,LS,2002,143250,Gasoline,Silver,Beige,1,1,4999,252.0,3.9,8.0,Gasoline,1.0,4.0
2,Chevrolet,Silverado,2002,136731,E85 Flex Fuel,Blue,Gray,0,1,13900,320.0,5.3,8.0,Flex,1.0,4.0
3,Genesis,G90,2017,19500,Gasoline,Black,Black,0,1,45000,420.0,5.0,8.0,Gasoline,1.0,8.0
4,Mercedes-Benz,Metris,2021,7388,Gasoline,Black,Beige,0,1,97500,208.0,2.0,4.0,Gasoline,1.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade,2017,49000,Gasoline,White,Beige,0,1,27500,420.0,6.2,8.0,Gasoline,1.0,8.0
188529,Mercedes-Benz,AMG,2018,28600,Gasoline,White,Black,1,1,30000,385.0,3.0,6.0,Gasoline,1.0,8.0
188530,Mercedes-Benz,AMG,2021,13650,Gasoline,White,Black,0,1,86900,469.0,4.0,8.0,Gasoline,1.0,7.0
188531,Audi,S5,2022,13895,Gasoline,Gray,Black,0,0,84900,333.0,3.0,6.0,Missing,1.0,1.0
188532,Porsche,Macan,2016,59500,Gasoline,White,Black,0,1,28995,252.0,2.0,4.0,Gasoline,1.0,7.0

In [ ]:
model = Modeling(CatBoostRegressor())
model.find_hyperparams(res_df)
pred = model.model_fit_predict(res_df)
pred

[I 2026-04-29 15:50:13,319] A new study created in memory with name: no-name-6366216c-e15d-47b0-a559-e98388234a44

  0%|          | 0/10 [00:00<?, ?it/s]

0:	learn: 80222.9604104	test: 82357.2383611	best: 82357.2383611 (0)	total: 278ms	remaining: 4m 26s
100:	learn: 74776.4770043	test: 77239.8825201	best: 77239.8825201 (100)	total: 12.3s	remaining: 1m 44s
200:	learn: 74364.5555529	test: 77122.3520023	best: 77121.9374681 (199)	total: 21.6s	remaining: 1m 21s
300:	learn: 73987.2043225	test: 77087.3528569	best: 77083.5763069 (264)	total: 29.9s	remaining: 1m 5s
400:	learn: 73625.6052370	test: 77096.9512652	best: 77081.3747376 (320)	total: 40.1s	remaining: 55.9s
500:	learn: 73131.9032022	test: 77154.4873164	best: 77081.3747376 (320)	total: 48s	remaining: 44s
600:	learn: 72643.8472455	test: 77216.3092019	best: 77081.3747376 (320)	total: 58s	remaining: 34.7s
700:	learn: 72314.2808427	test: 77234.0907308	best: 77081.3747376 (320)	total: 1m 8s	remaining: 25.2s
800:	learn: 72079.2712239	test: 77284.6171874	best: 77081.3747376 (320)	total: 1m 16s	remaining: 15.1s
900:	learn: 71791.8790210	test: 77351.5437350	best: 77081.3747376 (320)	total: 1m 26s	remaining: 5.65s
959:	learn: 71675.4391455	test: 77364.2848364	best: 77081.3747376 (320)	total: 1m 30s	remaining: 0us

bestTest = 77081.37474
bestIteration = 320

Shrink model to first 321 iterations.
[I 2026-04-29 15:51:46,021] Trial 0 finished with value: 19745.375626823017 and parameters: {'iterations': 960, 'learning_rate': 0.08035097503478011, 'depth': 4, 'l2_leaf_reg': 0.18189506293617672, 'bagging_temperature': 0.4124518044799049, 'random_strength': 0.2573123769339861, 'border_count': 247}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 78924.0405735	test: 81096.1368432	best: 81096.1368432 (0)	total: 237ms	remaining: 3m 21s
100:	learn: 69392.7257256	test: 77304.0452837	best: 77163.6978744 (64)	total: 21.7s	remaining: 2m 40s
200:	learn: 64458.6471793	test: 78163.2530310	best: 77163.6978744 (64)	total: 42.2s	remaining: 2m 16s
300:	learn: 60170.0971860	test: 78746.5252090	best: 77163.6978744 (64)	total: 1m 4s	remaining: 1m 57s
400:	learn: 56970.6628349	test: 79288.1961247	best: 77163.6978744 (64)	total: 1m 25s	remaining: 1m 36s
500:	learn: 54659.3749169	test: 79813.4325395	best: 77163.6978744 (64)	total: 1m 47s	remaining: 1m 15s
600:	learn: 51972.1219292	test: 80231.4978900	best: 77163.6978744 (64)	total: 2m 9s	remaining: 53.5s
700:	learn: 49838.6508657	test: 80834.5771854	best: 77163.6978744 (64)	total: 2m 29s	remaining: 31.8s
800:	learn: 48274.9241829	test: 80998.5220369	best: 77163.6978744 (64)	total: 2m 52s	remaining: 10.5s
849:	learn: 47562.4483579	test: 81114.3833134	best: 77163.6978744 (64)	total: 3m 2s	remaining: 0us

bestTest = 77163.69787
bestIteration = 64

Shrink model to first 65 iterations.
[I 2026-04-29 15:54:49,212] Trial 1 finished with value: 19868.789163058176 and parameters: {'iterations': 850, 'learning_rate': 0.2732620317417689, 'depth': 8, 'l2_leaf_reg': 0.39889493469024306, 'bagging_temperature': 0.8852109731126705, 'random_strength': 4.2517789617764885, 'border_count': 130}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 80868.2050064	test: 82974.1029012	best: 82974.1029012 (0)	total: 239ms	remaining: 3m 51s
100:	learn: 79281.2782708	test: 81452.9624532	best: 81452.9624532 (100)	total: 11.2s	remaining: 1m 36s
200:	learn: 78168.3058670	test: 80378.9283706	best: 80378.9283706 (200)	total: 22.3s	remaining: 1m 25s
300:	learn: 77374.7168896	test: 79606.6840533	best: 79606.6840533 (300)	total: 34.1s	remaining: 1m 15s
400:	learn: 76815.0076277	test: 79061.7828024	best: 79061.7828024 (400)	total: 45.5s	remaining: 1m 4s
500:	learn: 76410.1688216	test: 78674.2858469	best: 78674.2858469 (500)	total: 57s	remaining: 53.2s
600:	learn: 76104.7111713	test: 78383.6236409	best: 78383.6236409 (600)	total: 1m 9s	remaining: 42.3s
700:	learn: 75862.1430688	test: 78155.6556750	best: 78155.6556750 (700)	total: 1m 20s	remaining: 30.9s
800:	learn: 75680.0080290	test: 77984.2963713	best: 77984.2963713 (800)	total: 1m 32s	remaining: 19.5s
900:	learn: 75527.8853801	test: 77842.1766385	best: 77842.1766385 (900)	total: 1m 40s	remaining: 7.58s
968:	learn: 75443.6932712	test: 77761.6715445	best: 77761.6715445 (968)	total: 1m 48s	remaining: 0us

bestTest = 77761.67154
bestIteration = 968

[I 2026-04-29 15:56:38,799] Trial 2 finished with value: 20545.446220017406 and parameters: {'iterations': 969, 'learning_rate': 0.002097178405190751, 'depth': 5, 'l2_leaf_reg': 0.19210411928215718, 'bagging_temperature': 0.38483876336918255, 'random_strength': 0.03351415166170373, 'border_count': 149}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 79752.0146868	test: 81905.6048120	best: 81905.6048120 (0)	total: 221ms	remaining: 5m 38s
100:	learn: 69677.0215908	test: 77783.5675599	best: 77247.8838270 (34)	total: 20.6s	remaining: 4m 51s
200:	learn: 66053.5068882	test: 78251.2948150	best: 77247.8838270 (34)	total: 43.5s	remaining: 4m 47s
300:	learn: 62733.9919896	test: 78578.3849810	best: 77247.8838270 (34)	total: 1m 4s	remaining: 4m 23s
400:	learn: 60458.4840212	test: 78932.7490571	best: 77247.8838270 (34)	total: 1m 27s	remaining: 4m 6s
500:	learn: 58657.0164692	test: 78978.7708885	best: 77247.8838270 (34)	total: 1m 48s	remaining: 3m 42s
600:	learn: 57234.4350492	test: 79074.2739438	best: 77247.8838270 (34)	total: 2m 11s	remaining: 3m 22s
700:	learn: 55324.2492790	test: 79193.5213512	best: 77247.8838270 (34)	total: 2m 32s	remaining: 3m
800:	learn: 53650.3724241	test: 79321.8794784	best: 77247.8838270 (34)	total: 2m 54s	remaining: 2m 38s
900:	learn: 52349.4284440	test: 79368.2803577	best: 77247.8838270 (34)	total: 3m 16s	remaining: 2m 17s
1000:	learn: 51244.5430890	test: 79498.2479277	best: 77247.8838270 (34)	total: 3m 38s	remaining: 1m 55s
1100:	learn: 50290.8134298	test: 79561.1004519	best: 77247.8838270 (34)	total: 4m	remaining: 1m 33s
1200:	learn: 49377.8935073	test: 79671.0751356	best: 77247.8838270 (34)	total: 4m 20s	remaining: 1m 11s
1300:	learn: 48637.8263297	test: 79712.9725735	best: 77247.8838270 (34)	total: 4m 44s	remaining: 50.1s
1400:	learn: 47446.9280268	test: 79849.2746316	best: 77247.8838270 (34)	total: 5m 5s	remaining: 28.2s
1500:	learn: 46527.3329770	test: 79976.5626296	best: 77247.8838270 (34)	total: 5m 29s	remaining: 6.36s
1529:	learn: 46320.3213953	test: 79995.3722717	best: 77247.8838270 (34)	total: 5m 34s	remaining: 0us

bestTest = 77247.88383
bestIteration = 34

Shrink model to first 35 iterations.
[I 2026-04-29 16:02:14,384] Trial 3 finished with value: 19776.738941315023 and parameters: {'iterations': 1530, 'learning_rate': 0.1256315583743012, 'depth': 8, 'l2_leaf_reg': 0.1235279650834051, 'bagging_temperature': 0.35338525236666773, 'random_strength': 0.10235366587519674, 'border_count': 114}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 80239.1546357	test: 82399.4130561	best: 82399.4130561 (0)	total: 259ms	remaining: 4m 50s
100:	learn: 71547.3858744	test: 77171.8775238	best: 77148.5080539 (60)	total: 25.9s	remaining: 4m 22s
200:	learn: 68800.1191732	test: 77635.3990159	best: 77148.5080539 (60)	total: 52s	remaining: 3m 58s
300:	learn: 66486.7822656	test: 77811.4619397	best: 77148.5080539 (60)	total: 1m 15s	remaining: 3m 26s
400:	learn: 64835.3478743	test: 78095.0183189	best: 77148.5080539 (60)	total: 1m 42s	remaining: 3m 5s
500:	learn: 63140.6857442	test: 78257.7042455	best: 77148.5080539 (60)	total: 2m 10s	remaining: 2m 41s
600:	learn: 61582.9457491	test: 78351.3076353	best: 77148.5080539 (60)	total: 2m 36s	remaining: 2m 15s
700:	learn: 60095.9522230	test: 78502.1727131	best: 77148.5080539 (60)	total: 3m 1s	remaining: 1m 49s
800:	learn: 58608.7057776	test: 78699.3521589	best: 77148.5080539 (60)	total: 3m 28s	remaining: 1m 23s
900:	learn: 57189.4694051	test: 78904.5060954	best: 77148.5080539 (60)	total: 3m 55s	remaining: 57.9s
1000:	learn: 55875.9654251	test: 79089.3416831	best: 77148.5080539 (60)	total: 4m 21s	remaining: 31.9s
1100:	learn: 54803.6646641	test: 79247.0451233	best: 77148.5080539 (60)	total: 4m 45s	remaining: 5.71s
1122:	learn: 54510.5898419	test: 79319.9739267	best: 77148.5080539 (60)	total: 4m 52s	remaining: 0us

bestTest = 77148.50805
bestIteration = 60

Shrink model to first 61 iterations.
[I 2026-04-29 16:07:08,181] Trial 4 finished with value: 19765.415723744092 and parameters: {'iterations': 1123, 'learning_rate': 0.06325399059309317, 'depth': 9, 'l2_leaf_reg': 0.26351540560791575, 'bagging_temperature': 0.30307827229494533, 'random_strength': 0.012395405560614187, 'border_count': 125}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 79755.8122727	test: 81941.2176691	best: 81941.2176691 (0)	total: 224ms	remaining: 4m 25s
100:	learn: 73669.7450483	test: 76995.9268351	best: 76995.9199645 (99)	total: 17.2s	remaining: 3m 4s
200:	learn: 72500.3019626	test: 77010.0103611	best: 76995.9199645 (99)	total: 35.4s	remaining: 2m 52s
300:	learn: 71022.1460815	test: 77084.6782351	best: 76985.8481623 (203)	total: 56.9s	remaining: 2m 46s
400:	learn: 70133.4944607	test: 77079.5622302	best: 76985.8481623 (203)	total: 1m 15s	remaining: 2m 27s
500:	learn: 69076.5408052	test: 77158.7761007	best: 76985.8481623 (203)	total: 1m 35s	remaining: 2m 9s
600:	learn: 68279.1500175	test: 77267.7785844	best: 76985.8481623 (203)	total: 1m 56s	remaining: 1m 52s
700:	learn: 67391.5353794	test: 77385.9199994	best: 76985.8481623 (203)	total: 2m 15s	remaining: 1m 33s
800:	learn: 66064.2858130	test: 77498.4348859	best: 76985.8481623 (203)	total: 2m 35s	remaining: 1m 14s
900:	learn: 65082.4185439	test: 77662.9273155	best: 76985.8481623 (203)	total: 2m 57s	remaining: 55.4s
1000:	learn: 64242.4970043	test: 77687.8288842	best: 76985.8481623 (203)	total: 3m 16s	remaining: 35.7s
1100:	learn: 63603.6438766	test: 77730.5725155	best: 76985.8481623 (203)	total: 3m 35s	remaining: 16.1s
1182:	learn: 62652.7115786	test: 78089.7412843	best: 76985.8481623 (203)	total: 3m 53s	remaining: 0us

bestTest = 76985.84816
bestIteration = 203

Shrink model to first 204 iterations.
[I 2026-04-29 16:11:03,645] Trial 5 finished with value: 19783.583602717652 and parameters: {'iterations': 1183, 'learning_rate': 0.12655586495691856, 'depth': 8, 'l2_leaf_reg': 3.272541001057116, 'bagging_temperature': 0.3127012383223058, 'random_strength': 3.624538541293259, 'border_count': 166}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 80878.7910424	test: 82984.1399725	best: 82984.1399725 (0)	total: 144ms	remaining: 1m 21s
100:	learn: 80102.8609864	test: 82232.3541761	best: 82232.3541761 (100)	total: 9.32s	remaining: 43.3s
200:	learn: 79442.9391258	test: 81593.8297671	best: 81593.8297671 (200)	total: 21s	remaining: 38.6s
300:	learn: 78880.7016387	test: 81050.9784574	best: 81050.9784574 (300)	total: 32.4s	remaining: 29s
400:	learn: 78415.5420137	test: 80603.3862265	best: 80603.3862265 (400)	total: 43.6s	remaining: 18.4s
500:	learn: 78025.3675118	test: 80224.9915065	best: 80224.9915065 (500)	total: 53s	remaining: 7.3s
569:	learn: 77791.6621382	test: 79999.1129112	best: 79999.1129112 (569)	total: 1m 1s	remaining: 0us

bestTest = 79999.11291
bestIteration = 569

[I 2026-04-29 16:12:06,472] Trial 6 finished with value: 24127.163733439313 and parameters: {'iterations': 570, 'learning_rate': 0.0011313233195072727, 'depth': 5, 'l2_leaf_reg': 0.993831880974809, 'bagging_temperature': 0.09256071851025871, 'random_strength': 5.749635019008494, 'border_count': 176}. Best is trial 0 with value: 19745.375626823017.
0:	learn: 79819.1158742	test: 82004.3948156	best: 82004.3948156 (0)	total: 292ms	remaining: 2m 59s
100:	learn: 71549.0737308	test: 76931.3601697	best: 76924.1471435 (78)	total: 31.7s	remaining: 2m 41s
200:	learn: 69525.7369259	test: 77215.7982230	best: 76924.1471435 (78)	total: 1m 5s	remaining: 2m 15s
300:	learn: 67481.3216386	test: 77341.9418976	best: 76924.1471435 (78)	total: 1m 41s	remaining: 1m 46s
400:	learn: 65822.8597271	test: 77398.7759410	best: 76924.1471435 (78)	total: 2m 16s	remaining: 1m 13s
500:	learn: 64567.4194035	test: 77477.9040384	best: 76924.1471435 (78)	total: 2m 51s	remaining: 39.5s
600:	learn: 62796.0373880	test: 77602.3476478	best: 76924.1471435 (78)	total: 3m 29s	remaining: 5.24s
615:	learn: 62497.6673105	test: 77636.6560444	best: 76924.1471435 (78)	total: 3m 34s	remaining: 0us

bestTest = 76924.14714
bestIteration = 78

Shrink model to first 79 iterations.
[I 2026-04-29 16:15:41,972] Trial 7 finished with value: 19642.968942533098 and parameters: {'iterations': 616, 'learning_rate': 0.11144130676641668, 'depth': 10, 'l2_leaf_reg': 2.1607056846587223, 'bagging_temperature': 0.07783929637021458, 'random_strength': 0.23472460190957806, 'border_count': 84}. Best is trial 7 with value: 19642.968942533098.
0:	learn: 80765.2414458	test: 82874.7366076	best: 82874.7366076 (0)	total: 210ms	remaining: 6m 53s
100:	learn: 75546.0032486	test: 78091.1878133	best: 78091.1878133 (100)	total: 24.5s	remaining: 7m 32s
200:	learn: 74410.7114487	test: 77398.5914619	best: 77398.5914619 (200)	total: 45.3s	remaining: 6m 37s
300:	learn: 73844.6201889	test: 77195.0129226	best: 77195.0129226 (300)	total: 1m 7s	remaining: 6m 13s
400:	learn: 73523.5728672	test: 77116.5799388	best: 77116.5799388 (400)	total: 1m 27s	remaining: 5m 40s
500:	learn: 73242.6662689	test: 77058.7111368	best: 77058.7111368 (500)	total: 1m 45s	remaining: 5m 9s
600:	learn: 72946.3412099	test: 77031.9632727	best: 77031.9632727 (600)	total: 2m 6s	remaining: 4m 46s
700:	learn: 72689.0144172	test: 77004.8577446	best: 77004.7849538 (698)	total: 2m 26s	remaining: 4m 23s
800:	learn: 72402.9568322	test: 76986.5517953	best: 76983.7981567 (766)	total: 2m 44s	remaining: 3m 58s
900:	learn: 71868.8664867	test: 76973.4725352	best: 76972.1372360 (887)	total: 3m 6s	remaining: 3m 39s
1000:	learn: 71183.6402537	test: 76975.3386697	best: 76967.0108214 (971)	total: 3m 29s	remaining: 3m 21s
1100:	learn: 70514.4254961	test: 77037.9944338	best: 76967.0108214 (971)	total: 3m 54s	remaining: 3m 4s
1200:	learn: 69967.7046061	test: 77029.2614670	best: 76967.0108214 (971)	total: 4m 17s	remaining: 2m 43s
1300:	learn: 69466.8773808	test: 77038.8115741	best: 76967.0108214 (971)	total: 4m 43s	remaining: 2m 24s
1400:	learn: 68936.2938215	test: 77085.2913731	best: 76967.0108214 (971)	total: 5m 9s	remaining: 2m 4s
1500:	learn: 68408.1868453	test: 77057.2229516	best: 76967.0108214 (971)	total: 5m 33s	remaining: 1m 42s
1600:	learn: 67893.1750065	test: 77062.1180500	best: 76967.0108214 (971)	total: 5m 59s	remaining: 1m 21s
1700:	learn: 67381.8268678	test: 77076.9968746	best: 76967.0108214 (971)	total: 6m 25s	remaining: 59.5s
1800:	learn: 66959.9227464	test: 77093.1291892	best: 76967.0108214 (971)	total: 6m 49s	remaining: 37.1s
1900:	learn: 66561.7865798	test: 77103.1467722	best: 76967.0108214 (971)	total: 7m 15s	remaining: 14.4s
1963:	learn: 66274.7644148	test: 77118.1818851	best: 76967.0108214 (971)	total: 7m 30s	remaining: 0us

bestTest = 76967.01082
bestIteration = 971

Shrink model to first 972 iterations.
[I 2026-04-29 16:23:15,101] Trial 8 finished with value: 19680.808166737657 and parameters: {'iterations': 1964, 'learning_rate': 0.014254130157683273, 'depth': 9, 'l2_leaf_reg': 0.25409468675440483, 'bagging_temperature': 0.03174945536646545, 'random_strength': 3.2863063103324697, 'border_count': 35}. Best is trial 7 with value: 19642.968942533098.
0:	learn: 79618.9513880	test: 81788.2747415	best: 81788.2747415 (0)	total: 208ms	remaining: 2m 32s
100:	learn: 73406.6016534	test: 77116.3156498	best: 77116.3156498 (100)	total: 20.2s	remaining: 2m 6s
200:	learn: 72799.7998487	test: 77072.8516394	best: 77070.4343830 (196)	total: 36.1s	remaining: 1m 35s
300:	learn: 71886.9870556	test: 77080.1594962	best: 77053.7113736 (219)	total: 53.5s	remaining: 1m 16s
400:	learn: 71142.3421638	test: 77139.7352472	best: 77053.7113736 (219)	total: 1m 10s	remaining: 58.7s
500:	learn: 70506.5954475	test: 77161.4016919	best: 77053.7113736 (219)	total: 1m 29s	remaining: 41.2s
600:	learn: 69896.7343223	test: 77214.6708360	best: 77053.7113736 (219)	total: 1m 47s	remaining: 23.6s
700:	learn: 69400.2242662	test: 77262.7882805	best: 77053.7113736 (219)	total: 2m 6s	remaining: 5.79s
732:	learn: 69206.6064136	test: 77283.1827322	best: 77053.7113736 (219)	total: 2m 12s	remaining: 0us

bestTest = 77053.71137
bestIteration = 219

Shrink model to first 220 iterations.
[I 2026-04-29 16:25:28,443] Trial 9 finished with value: 19647.282766936103 and parameters: {'iterations': 733, 'learning_rate': 0.13652166508707514, 'depth': 8, 'l2_leaf_reg': 7.42473098980574, 'bagging_temperature': 0.18683941159866357, 'random_strength': 0.0353624325734336, 'border_count': 232}. Best is trial 7 with value: 19642.968942533098.
Best params: {'iterations': 616, 'learning_rate': 0.11144130676641668, 'depth': 10, 'l2_leaf_reg': 2.1607056846587223, 'bagging_temperature': 0.07783929637021458, 'random_strength': 0.23472460190957806, 'border_count': 84}
Best score: 19642.968942533098

TypeError: 'CatBoostRegressor' object is not callable